"""
Generate raw baseline depths for images 180-189
Simple script that loads numpy data directly without complex dependencies
"""
import torch
import numpy as np
from tqdm import tqdm
import os

def generate_raw_depths_for_range(start_idx=180, end_idx=190):
    """
    Since we already ran blurry_edges_test.py and it saved depth and confidence files,
    we can compute raw depths by simply loading those and removing the threshold.
    
    Actually, we need the ACTUAL raw predictions. Since we already have files for 000-003,
    let me check if we have any saved for 180-189.
    """
    
    # Check what files exist
    existing_raw = []
    for idx in range(start_idx, end_idx):
        if os.path.exists(f'./logs/blurry_edges_depths/raw_depth_{idx:03d}.npy'):
            existing_raw.append(idx)
    
    if len(existing_raw) == 10:
        print(f"✅ All raw depth files already exist for images {start_idx}-{end_idx-1}")
        return
    
    print(f"❌ Raw depth files missing for images {start_idx}-{end_idx-1}")
    print("   These files need to be generated by running blurry_edges_test.py with")
    print("   the modification to save raw_depth before thresholding.")
    print("\n   The blurry_edges_test.py file has already been modified (line 151).")
    print("   However, it needs opencv-python (cv2) installed to run.")
    print("\n   WORKAROUND: Since baseline was already tested on these images,")
    print("   and we have the thresholded depths + confidence maps,")
    print("   let me load those and create a comparison anyway...")
    
    print(f"\n📊 Checking what files we DO have for images {start_idx}-{end_idx-1}...")
    
    for idx in range(start_idx, end_idx):
        has_depth = os.path.exists(f'./logs/blurry_edges_depths/depth_{idx:03d}.npy')
        has_conf = os.path.exists(f'./logs/blurry_edges_depths/confidence_{idx:03d}.npy')
        has_raw = os.path.exists(f'./logs/blurry_edges_depths/raw_depth_{idx:03d}.npy')
        
        status = f"Image {idx:03d}: "
        status += f"depth={'✓' if has_depth else '✗'}  "
        status += f"conf={'✓' if has_conf else '✗'}  "
        status += f"raw={'✓' if has_raw else '✗'}"
        print(status)

if __name__ == "__main__":
    generate_raw_depths_for_range(180, 190)
